name: dinedecide
description: "DineDecide - A Flutter app to help you decide what to eat."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.7
  shared_preferences: ^2.3.5
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.4
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/logo.png
  android_12:
    image: assets/icon/logo.png
    color: "#FFFFFF"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
